development:
  stripe_secret_key: 'sk_test_51Jf4GEFFrya4Rc8JJYaIJX1z554ToSyIu1DWSE50jX6JaWyohBIYJTfuzpyYX4PrtbMVDiJ4iQSU3QxvfxJ9hJzH00sZW9uM0i'
  stripe_publishable_key: 'pk_test_51Jf4GEFFrya4Rc8JUuxAqZKFlYiUvsB9UYkbVYNdzuwP6SFKBMTtUOzBO5QttZBlmazVCyU6MRTkdJQjTdLdZ0sg00usxEQbZq'

production:
  stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
  stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'